[server]
maxUploadSize = 10

[theme]
base = "dark"
primaryColor = "#1ed760"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#1ed760"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
font = "Poppins"
headingFontWeights = [400, 300, 300, 300, 300, 300]
headingFontSizes = ["2rem", "2rem", "2rem", "2rem", "2rem"]
chartCategoricalColors = ["#ffc862", "#2d46b9", "#b49bc8"]

[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#696969"